### ISSUE TITLE
Class "LakM\Comments\Model" not found

### ISSUE THREAD

**Issue by topclaudy** [Lakshan-Madushanka/laravel-comments-admin-panel#4]
![Screenshot 2024-08-05 at 09 12 11](https://github.com/user-attachments/assets/f0c01af3-89de-4655-86d9-e1b5bd68bb92)

It should be `use LakM\Comments\ModelResolver as M;` at line 8

Can you please fix and release this?

**Comment by Lakshan-Madushanka** [comment]
@topclaudy Thanks for reporting this. I made some changes in commenter and forgot those effects to admin-panel.

**Comment by Lakshan-Madushanka** [comment]
Release [v1.0.3](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel/releases/tag/1.0.3)
